### ISSUE TITLE
Frontend Github Action schlägt fehl

### ISSUE THREAD

**Issue by benedictweis** [SE-TINF22B2/G5-DuoGradus#104]
Die Github Action die bei jeden Pull Request das Frontend validiert schlägt aktuell immer fehl (siehe z.B. diesen [PR](https://github.com/SE-TINF22B2/G5-DuoGradus/pull/102)). 

Ich weiß leider nicht konkret was dort das Problem ist, es das `npm test` Skript scheint das angular testing framework aufzurufen was wiederum scheinbar eine Chrome Instanz benötigt? Vielleicht ist es für end to end tests. 

Dieses Problem sollte behoben werden, nicht nur weil die Action nicht funktioniert, sondern auch weil sie bei jedem Run viele unnötige Action Runner Minuten verbrauchen.

Kannst du @Jstn2004 mir helfen dieses Problem zu beheben?

**Comment by Jstn2004** [comment]
Ich habe mal was bei der Test Konfiguration geändert. Die Test werden in den  Github Actions jetzt auch als **Success** angezeigt. Aber der Workflow hört dann nicht auf und geht nicht zum nächsten Schritt über.

**Comment by benedictweis** [comment]
Closed, da der ursprüngliche Fehler behoben ist und sich nun in #112 darum gekümmert wird
