### ISSUE TITLE
Prisma db migration "DATABASE_URL" default

### ISSUE THREAD

**Issue by benedictweis** [SE-TINF22B2/G5-DuoGradus#110]
Der Main ist gerade kaputt da wenn man `npm run db:reset` aufruft kommt folgender Fehler: 

```bash

> duogradus-backend@0.0.1 db:reset
> prisma migrate reset --force

Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database
Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:10
   | 
 9 |   provider = "sqlite"
10 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
[Context: getConfig]

Prisma CLI Version : 5.11.0
```

bevor weitere pull requests gestellt werden sollte dieser Fehler behoben werden.

Möglicherweise ist dieses Verhalten auch so vorhergesehen, falls ja sollte dokumentiert sein auf welchen wert die "DATABASE_URL" gesetzt werden sollte oder ein env file hinzugefügt werden oder ein default gesetzt werden.

Wenn man `export DATABASE_URL=file:./.database.dev.sqlite` setzt wird eine lokale sqlite Datenbank genutzt, ich schlage vor dies als default zu verwenden oder es irgendwie geartet zu dokumentieren

**Comment by henrybrink** [comment]
This was fixed by #102.
