### ISSUE TITLE
Implementation von Aufgaben

### ISSUE THREAD

**Issue by benedictweis** [SE-TINF22B2/G5-DuoGradus#126]

**Comment by henrybrink** [comment]
Die Aufgaben sind ein zentraler Bestandteil der Anwendung und der Benutzeroberfläche. Es gibt mehrere Arten von Aufgaben, aber alle erfüllen folgende Voraussetzungen:

- Jede Aufgabe ist an Bedingungen geknüpft, z.B. 1.000 Schritte in 1h erreichen.
- Ist eine Aufgabe erfüllt, dann werden die Punkte dem Nutzer gutgeschrieben.
- Eine Aufgabe kann mehrmals erfüllt werden, gibt aber nur noch die Hälfte der Punkte, wenn diese bereits einmal erfüllt wurde.

Die Aufgaben sind statisch, es ist also keine Konfiguration in der Anwendung vorgesehen. Die Aufgaben können z.B. in einer JSON-Datei gespeichert werden, alternativ ist auch eine Typescript-Datei denkbar. Alles ist hardcodiert, dynamische Aufgaben sind zeittechnisch nicht mehr realistisch.

**Comment by henrybrink** [comment]
(Aufgaben sind die "Tasks" aus der API)

**Comment by henrybrink** [comment]
Während der Implementierung sind mir einige Probleme an meinem ersten Entwurf aufgefallen, deswegen habe ich eine angepasste Version des Entwurfs implementiert:

- Die "Tasks" waren zuvor für die "start" und "stop" Funktion verantwortlich, da diese allerdings immer für alle Aufgaben gleich sind, habe ich diese in den TaskService überführt, da Dependency Injection mit einer einzelnen Task nicht funktionieren würde und so die Komplexität erhöhen würde.
- Die "validate" Methode nimmt nun zwei Parameter entgegen: Die Fitness-Daten beim Start der Aufgabe und die Fitness-Daten am Ende, diese können entweder miteinander verglichen werden, oder spezielle Werte auf diesen analysiert werden (wenn kein Vergleich erfolgen soll, dann sollten nur die "aktuellen" Daten betrachtet werden). Dadurch muss die "Task"-Klasse die Daten nicht mehr selbst anfragen, was die Komplexität verringert und die Aufgaben unabhängiger macht

Der Prozess zum Starten einer Aufgabe läuft nun wie folgt ab:
```mermaid

sequenceDiagram

participant C as TaskController
participant S as TaskService
participant F as FitnessSerivce
participant T as Task
participant R as TaskRepository

C->>S: startTask(user, task)
activate C
activate S
S->>T: getInfo()
activate T
T-->>S: task info
deactivate T
S->>S: verify that the task exists
S->>F: get the current fitness data
activate F
F-->>S: fitness data
deactivate F
S-->>R: create task log with fitness data and start time
S-->>C: Task Info with status "started"
deactivate C
deactivate S
```

Beim Stoppen der Aufgabe passiert folgendes:
```mermaid

sequenceDiagram

participant C as TaskController
participant S as TaskService
participant F as FitnessSerivce
participant T as Task
participant R as TaskRepository

C->>S: stopTask(user, task)
activate C
activate S
S->>T: getInfo()
activate T
T-->>S: task info
deactivate T
S->>S: verify that task exists
S->>R: get task log
activate R
R-->>S: task log
deactivate R
S->>S: verify that task was started and is still running
S->>S: stop task
S->>S: save updated log with status pending
S->>S: schedule task validator
S-->>C: task log with status pending
deactivate S
deactivate C
```

Beim stoppen einer Task wird zunächst der neue Status "pending" zurückgegeben, im Hintergrund wird eine Aufgabe gestartet, mit der die Fitness-Daten nach Ablauf eines Timers (evtl. 3 Minuten) abgerufen werden und dann die tatsächliche Validierung erfolgt.

Dies erfolgt weiterhin in der "Task"-Klasse, über die Methode "validate". Diese gibt einen boolean zurück. *Achtung*: Die Methode ist synchron.

**Comment by benedictweis** [comment]
Das klingt sehr schlüssig für mich 👍. Vielen Dank.
