### ISSUE TITLE
Implementation von Zielen

### ISSUE THREAD

**Issue by benedictweis** [SE-TINF22B2/G5-DuoGradus#127]

**Comment by henrybrink** [comment]
s.h. #53

**Comment by henrybrink** [comment]
Um unser Backend zu Vereinfachen werden die Ziele direkt vom Fitness-Anbieter geladen, dabei sollen diese mind. 1x pro Stunde aktualisiert werden, allerdings ansonsten aus dem Cached geladen werden (um den Fitness-Anbieter nicht zu oft abzufragen).

Die Ziele sollen über den Endpoint "/goal" geladen werden (s.h. https://docs.duo-gradus.de/api/client.html)
