### ISSUE TITLE
Verschiedene Orte für Dokumentation

### ISSUE THREAD

**Issue by henrybrink** [SE-TINF22B2/G5-DuoGradus#131]
Derzeit haben wir mehre Orte in denen noch Dokumentation zu finden ist, diese sollten alle in die neue Dokumentation überführt werden.

obsolete Dokumentation: 
- "frontend/docs"
- "backend/docs"
- Wiki

Ich würde vorschlagen diese Ordner / Dateien entfernen und das Wiki zu deaktivieren / an die Dokumentation weiterzuleiten.

**Comment by benedictweis** [comment]
Im Wiki befindest sich bereits eine deprecated warning und ein Termin zu dem es abgeschaltet wird. Die frontend und backend Dokumentation war damals der Gedanke dass die Dinge die den Code direkt betreffen bzw. In Zukunft auch direkt aus dem Code generier werden könnte (besonders beim frontend) in separaten Ordnern sind. Wenn es allen lieber ist das auch in der Projekt Dokumentation zu haben ändere ich das sofort.

**Comment by benedictweis** [comment]
Aus dem letzten Users PR ziehe ich jetzt mal dass du dafür bist alle Dokumentation in den docs folder zu tun @henrybrink. Mit deinem Einverständnis ziehe ich dann die restlichen Dateien auch noch da rein.

**Comment by benedictweis** [comment]
Alles klar, dann mache ich das so.

**Comment by benedictweis** [comment]
Geschlossen durch #148.
