### ISSUE TITLE
Integrationspartner auswählen / überprüfen

### ISSUE THREAD

**Issue by henrybrink** [SE-TINF22B2/G5-DuoGradus#136]
Für die Integration von Drittanbietern für Fitness-Daten stehen verschiedene Integrationspartner zur Verfügung.

Wie in der [Dokumentation](https://docs.duo-gradus.de/project/requirements.html#integration-mit-drittanbietern-zur-datenerhebung-pm-1) beschrieben, soll evaluiert werden, welcher dieser Integrationspartner sinnvoll für eine Beispiel-Implementation ist.

**Comment by henrybrink** [comment]
@benedictweis Ich würde vorschlagen zunächst FitBit zu verwenden, da ich da bereits einen App-Zugang anlegen konnte.

**Comment by henrybrink** [comment]
Wir können allerdings auch gerne noch ein zwei andere Anbieter ansehen und zumindest in das Konzept des Datenmodells mitaufnehmen / prüfen ob dieses auch mit diesen kompatibel ist.

**Comment by benedictweis** [comment]
> @benedictweis Ich würde vorschlagen zunächst FitBit zu verwenden, da ich da bereits einen App-Zugang anlegen konnte.

Finde ich gut, du hast ja ein entsprechendes Gerät 😉

**Comment by benedictweis** [comment]
> Wir können allerdings auch gerne noch ein zwei andere Anbieter ansehen und zumindest in das Konzept des Datenmodells mitaufnehmen / prüfen ob dieses auch mit diesen kompatibel ist. 

Das ist natürlich eine Überlegung wert aber ich denke erstmal Fitbit und dann schauen wir wie das gelaufen ist bzw. ob man dass datenmodell nochmal signifikant anpassen muss um mit anderen Anbietern zu arbeiten.

**Comment by benedictweis** [comment]
Also hast du von meiner Seite das Go für FitBit

**Comment by henrybrink** [comment]
Perfekt, dann legen wir mal "FitBit" fest.
