### ISSUE TITLE
Replikation von Drittanbieter-Daten

### ISSUE THREAD

**Issue by henrybrink** [SE-TINF22B2/G5-DuoGradus#140]
Sofern ein einheitliches Austauschformat für #139 gefunden wurde, soll die Persistenz-Ebene angepasst werden, sodass die in #139 erstellten Austauschdaten gespeichert werden können.

Folgende Daten sollen gespeichert werden:
- Aktivitäten
- Schritte (Tag)

Es soll für den Nutzer möglich sein diese Informationen abzurufen, für Aktivitäten existiert bereits ein Endpunkt, für Schritte soll dieser hinzugefügt werden (beispielsweise /activities/steps oder /steps). -Der Nutzer darf eigene Aktivitäten erstellen-, Schritte sind hingegen schreibgeschützt.

**Update**:
Es soll folgendes gespeichert werden:
- Anzahl der Schritte, höchstens eine Stunde alt

Weitere Anforderungen lassen wir erstmal weg.

Zudem soll es möglich sein die Daten "zwangsweise" zu aktualisieren, also z.B. beim Start und beim Ende einer Aktivität

**Comment by benedictweis** [comment]
Geschlossen da der wesentliche Teil implementiert ist
