### ISSUE TITLE
Zeiterfassungsberichte per Github Action

### ISSUE THREAD

**Issue by henrybrink** [SE-TINF22B2/G5-DuoGradus#141]
Derzeit werden die Statusberichte manuell generiert. Dies soll in Zukunft per GitHub Action möglich sein.
Die dafür notwendige Action soll:
- Am Dienstag-Abend ausgeführt werden (vor der Präsentation der Statusberichte)
- Auch manuell ausgeführt werden können

Für den Zugang zum Zeiterfassungssystem erhält die Action einen technischen Benutzer im Zeiterfassungssystem.

**Comment by benedictweis** [comment]
Finde ich eine sehr gute Idee, wenn ich das Übernehmen soll dann sag gerne bescheid, dann kannst du dich den backend aufgaben widmen.

**Comment by henrybrink** [comment]
Ich wollte das eigentlich im Zug machen, aber leider wurde die Zugfahrt ja unterbrochen, dementsprechend konnte ich das nicht weiter fortführen - ich habe aber einen Beginn

**Comment by henrybrink** [comment]
Done
