### ISSUE TITLE
Feedback Projektbesprechung 16.05.

### ISSUE THREAD

**Issue by benedictweis** [SE-TINF22B2/G5-DuoGradus#188]
Bei der Projektbesprechung mit @roland-KA am 16.05.2024 ergab sich folgendes Feedback was nun umgesetzt werden muss:

- [x] Mockup Pfade in den `docs` führen ins nichts
- [x] Überprüfen ob alle Github Labels zutreffend sind auf das Projekt
- [ ] Im Frontend sollen nur die Komponenten im Storybook #186 vorkommen die auch konkreten use cases zugeordnet werden können
- [x] #194
- [ ] Projektplanung verbessern und mit allen Projektmitgliedern absprechen
- [x] #214
- [ ] `README.md` des `frontend`s und des `backend`s überarbeiten, es sollte aufgeführt sein, welche Dateien generiert sind, wie man das Projekt baut und ausführt und wie man Änderungen korrekt vornimmt (Teil von #91)
- [x] Issue Templates damit keiner vergisst Issues mit Text zu versehen
- [x] Pull-Requets Templates damit keiner vergisst Pull-Requests mit Text zu versehen

@henrybrink habe ich noch etwas vergessen?

**Comment by henrybrink** [comment]
Nope - das sieht vollständig aus, Herr Weis!

**Comment by roland-KA** [comment]
Noch ein paar Ergänzungen meinerseits:

> Im Frontend sollen nur die Komponenten im Storybook https://github.com/SE-TINF22B2/G5-DuoGradus/issues/186 vorkommen die auch konkreten use cases zugeordnet werden können

Hier ging es in der Tat einerseits um den Bezug zu den Anforderungen. Außerdem war mir ein Anliegen, nur auf einer sinnvollen Granularitätsebene zu dokumentieren (also nicht jeden Button und jedes Label einzeln). Damit ist niemandem geholfen und es bläht den Umfang der Doku künstlich auf.

> Projektplanung verbessern und mit allen Projektmitgliedern absprechen

Verbessern in dem Sinne, dass eine Planung bis Fertigstellung entsteht (an der man auch erkennen kann, ob der Fertigstellungszeitpunkt noch im Semester oder weit danach liegt. 

Außerdem ist Projektplanung immer eine Teamaufgabe; nie eines Einzelnen. Aufwandsschätzungen, Termin- und Ressourcenplanung (d.h. Zuordnung von Personen zu Aufgaben) sollte immer gemeinsam im Team vorgenommen werden.

> README.md des frontends und des backends überarbeiten, es sollte aufgeführt sein, welche Dateien generiert sind, wie man das Projekt baut und ausführt und wie man Änderungen korrekt vornimmt (Teil von https://github.com/SE-TINF22B2/G5-DuoGradus/issues/91)

Ein neues Teammitlglied sollte sich schnell einen Überblick verschaffen können, welche Technologien und Werkzeuge verwendet werden und in welcher Weise sie im Projekt angewendet werden (sollen). Es kann z.B. sein, dass ein Fullstack-Framework genutzt wird, daraus aber (bewusst) nicht alle Elemente verwendet werden. Das muss ein Neuer wissen, sonst macht er das garantiert falsch.

Außerdem sollte eine solche Doku klar machen, nach welchen Systematiken, welche Änderungen/Ergänzungen im Code durchgeführt werden (sollen).

**Comment by benedictweis** [comment]
Vielen Dank, wir setzen uns ans Umsetzen 😉
