### ISSUE TITLE
Einheitliche Sprache im Frontend

### ISSUE THREAD

**Issue by wwwLuis** [SE-TINF22B2/G5-DuoGradus#191]
Die Sprache im Frontend sollte einheitlich Deutsch oder Englisch sein.
@benedictweis @henrybrink @OG-NI wäre euch die App in Deutsch oder Englisch lieber?

**Comment by benedictweis** [comment]
Also von uns aus könnt ihr das machen wir ihr wollt, ich wäre für Deutsch da ja auch die Dokumentation auf Deutsch ist.
