### ISSUE TITLE
Architektur festlegen

### ISSUE THREAD

**Issue by benedictweis** [SE-TINF22B2/G5-DuoGradus#20]
Wenn alle nicht optionalen Anforderungen festgelegt wurden und diese in Teilschritte zerlegt wurden, soll eine Architektur festgelegt werden. Folgende Teilschritte sind hierfür von Nöten:

- [x] Kommunikation zwischen Frontend und Backend festlegen (API)
- [x] Externe services identifizieren und in die Architektur mit einplanen
- [x] Architektur Diagramm "Zeichnen"
- [x] Technologien auswählen und fundiert begründen

**Comment by henrybrink** [comment]
![Architekturentwurf](https://github.com/SE-TINF22B2/G5-DuoGradus/assets/20884220/80551c00-a5d2-4ed9-8a50-4ad1db909d55)

@OG-NI und ich haben schonmal angefangen mit dem Architekturentwurf. Hier einmal - für das Backend - die Übersicht mit den einzelnen Komponenten.

Noch nicht enthalten ist die API, die das Backend bereitstellt. Gerne Feedback

**Comment by benegamz** [comment]
Wow, das finde ich sehr gut! Lasst uns mal seinen input dazu mit in die Diskussion nehmen morgen.

**Comment by henrybrink** [comment]
Ich hab das Diagramm noch in unserem VP-Projekt auf dem DHBW-Server hochgeladen, sodass wir dort auch eine zentrale Version haben, an der wir Änderungen durchführen können.

**Comment by henrybrink** [comment]
![Backend_ ER-Diagramm](https://github.com/SE-TINF22B2/G5-DuoGradus/assets/20884220/60cacad0-b01a-4ac5-aa13-df48baba2d4b)

Ich hab auch schonmal ne Skizze für ein ER-Diagramm dort erstellt, allerdings erstmal nur mit drei Entitäten und einem View um das auszuprobieren.

**Comment by henrybrink** [comment]
![Backend_ ER-Diagramm](https://github.com/SE-TINF22B2/G5-DuoGradus/assets/20884220/b28e2749-5681-48ca-adbb-69fdd0cc8e9d)

![Architekturentwurf](https://github.com/SE-TINF22B2/G5-DuoGradus/assets/20884220/c5e1819c-4380-4fd6-b7c6-fdebef82f0c3)

Diagramme aktualisiert

**Comment by benedictweis** [comment]
Ich schließe dieses Issue da die Architektur im Grundsatz besteht. Weitere Anpassungen daran dann in separaten Issues.
