### ISSUE TITLE
Spoken Language in GitHub Issues

### ISSUE THREAD

**Issue by henrybrink** [SE-TINF22B2/G5-DuoGradus#202]
**Describe the bug**
There has been a discussion what language we should use in our issues. According to the documentation, we should use german for issues (https://docs.duo-gradus.de/development/project-guideline.html#verwendete-gesprochene-sprachen), but the new issue template is in english.

Should we stick to the language in the issue template or translate the issue template?

**To Reproduce**
1. Open GitHub
2. Create an issue

**Expected behavior**
A German issue template

**Screenshots**
I don't think I need screenshots for this.

**Additional context**
-

**Comment by benedictweis** [comment]
😂 Ja wie heute in der Projektbesprechung angesprochen werde ich die Templates noch anpassen bzw. übersetzen 😉

**Comment by henrybrink** [comment]
Das Template für die Pull-Requests ist jetzt auf Deutsch, aber die festgelegte Sprache ist auf Englisch ;)

**Comment by benedictweis** [comment]
Wurde behoben.
