### ISSUE TITLE
Code-Coverage anpassen

### ISSUE THREAD

**Issue by henrybrink** [SE-TINF22B2/G5-DuoGradus#203]
Derzeit haben wir sehr strikte Vorgaben für die Code-Coverage, die grundsätzlich auch sinnvoll sind.
Allerdings sind wir derzeit in der Endphase unseres Projekts und haben durch die strikten Anforderungen Probleme den Code rechtzeitig einzubringen.

Als Studentenprojekt wollen wir generell die Werkzeuge kennenlernen, allerdings bringt es uns nichts wenn wir deswegen keinen Fortschritt mehr erzielen können. Auch lassen sich viele Komponenten derzeit nicht sinnvoll testen.

Ich würde vorschlagen zunächst auf die Coverage als KPI zu verzichten und an den Stellen wo es sinnvoll möglich ist (und auch mit vertretbarem Zeitaufwand) und die Zeit lieber in ein Review zu stecken.

In unserem Rahmen dürfte dies vollkommen vertretbar sein :)

**Comment by benedictweis** [comment]
Ich bin auch dafür die coverage aus verify wegzulassen 👍
