### ISSUE TITLE
Frontend und Backend verheiraten

### ISSUE THREAD

**Issue by benedictweis** [SE-TINF22B2/G5-DuoGradus#217]
**Hat das Feature mit einem Problem zu tun? Falls ja, beschreibe.**
Frontend und Backend sind jeweils auf einem guten Stand, bis zur Projektpräsentation sollten diese aber zumindest auf irgendeine Weise miteinander verheiratet werden

**Beschreibe die Lösung die du gerne hättest**
Beide Teams sollten miteinander arbeiten, die API Spec muss dafür auf dem neusten Stand sein und ein gemeinsames Verständnis der App muss vorhanden sein.

**Weiterer Context**
Dieses "Feature" ist zentral für die Applikation und sollte zumindest in geringem Umfang eingebaut werden.

**Comment by benedictweis** [comment]
@henrybrink denkst du das Backend ist auf einem Stand auf dem wir es verheiraten können? Falls nein, welche Issues fehlen noch?

**Comment by henrybrink** [comment]
Nein, Aktivitäten fehlen noch, ich bin dabei

**Comment by henrybrink** [comment]
Registrierung fehlt auch noch

**Comment by benedictweis** [comment]
> Registrierung fehlt auch noch

Würde ich hier jetzt mal als optional betrachten, im Notfall bei der Demo einfach statisch
