### ISSUE TITLE
Big Picture

### ISSUE THREAD

**Issue by benegamz** [SE-TINF22B2/G5-DuoGradus#22]
Dem Anwender muss durch eine Beschreibung der Projektidee in Form eines "Big Pictures" klar werden, was die Applikation erreicht und welchen nutzen sie dem Anwender bietet ("Use Cases"). Die Beschreibung soll weiterhin eine Brücke zwischen dem Anwender und den konkreten, teils sehr technischen, Anforderungen schlagen.

Diese Beschreibung soll als [Github Wiki](https://github.com/SE-TINF22B2/G5-DuoGradus/wiki/Big-Picture) angelegt werden.

**Comment by benniloidl** [comment]
@henrybrink Vielen Dank für die Möglichkeit, dieses Projekt weiterzubringen und meine persönlichen Fähigkeiten zu erweitern. ❤️

**Comment by OG-NI** [comment]
Umfang: ca. 400 Wörter

**Comment by henrybrink** [comment]
Wie besprochen Start / Ausarbeitung in der nächsten Iteration aufgrund von Zeitgründen

**Comment by benegamz** [comment]
Ich finde den text sehr gut 👍. Ist es in eurem Sinne einen Teil des Textes auch im Readme zu veröffentlichen oder sollte dort nur die Projektidee platz finden?

**Comment by henrybrink** [comment]
Wir können den Text theoretisch auch im README.md veröffentlichen, allerdings würde ich da nur einen kleinen Ausschnitt als Beschreibung und dann eher technische / organisatorische Dinge aufschreiben.

**Comment by benegamz** [comment]
Closed, da done.
