### ISSUE TITLE
Projekt durchschauen und auf Abschlusspräsentation vorbereiten

### ISSUE THREAD

**Issue by benedictweis** [SE-TINF22B2/G5-DuoGradus#227]
**Hat das Feature mit einem Problem zu tun? Falls ja, beschreibe.**
Das Projekt sieht an stellen unfertig aus.

**Beschreibe die Lösung die du gerne hättest**
Das Projekt sollte durchgeschaut werden und gegebenenfalls verschönert/verbessert werden. Hierbei handelt es natürlich nur um sehr kleine Verbesserungen. Besonders die `Readme.md`'s sollten angepasst werden.

**Beschreibe Alternative Ansätze**
Keine.

**Weiterer Context**
Dies Sollte unserer Note dienlich sein.

**Comment by Jstn2004** [comment]
Sollten wir die Architektur nicht noch in die docs.duogradus hinzufügen? Und ist es nur bei mir so, dass die Bilder bei den User Interfaces nicht laden?

**Comment by benedictweis** [comment]
> Sollten wir die Architektur nicht noch in die docs.duogradus hinzufügen? Und ist es nur bei mir so, dass die Bilder bei den User Interfaces nicht laden? 

Die Architektur können wir gern hinzufügen und die Bilder laden bei mir.
