### ISSUE TITLE
Über Mockups diskutieren

### ISSUE THREAD

**Issue by benedictweis** [SE-TINF22B2/G5-DuoGradus#31]

**Comment by Jstn2004** [comment]
Ich hab nochmal bei den Mockups mit dem Farbdesign ein bisschen rumprobiert. Wie findet ihr das? 
![image](https://github.com/SE-TINF22B2/G5-DuoGradus/assets/135236159/7dfb58b3-ad8e-4987-be60-5455022ccd7f)

**Comment by benegamz** [comment]
Gefällt mir sehr gut!

**Comment by henrybrink** [comment]
Sieht gut aus, ich würd in der Titelleiste beim 1. & 2. Screen bei Weiß für den Titel bleiben, ähnlich wie im letzten Screen und das Grün dann als Akzentfarbe sonst perfekt!

**Comment by benegamz** [comment]
Neuste Mockups unter https://www.figma.com/file/l2Lz3Kdxe8IPPcDEplvrsv/DuoGradus?type=design&node-id=0-1&mode=design

**Comment by benedictweis** [comment]
Die Mockups sind jetzt soweit fertig, daher schließe ich dieses Issue.
