### ISSUE TITLE
Logo erstellen

### ISSUE THREAD

**Issue by benedictweis** [SE-TINF22B2/G5-DuoGradus#33]
Ein gutes Projekt braucht auch ein Logo! Ich schlage vor ein Logo im Format 1:1 zu designen, so wie einen Banner der unser Readme schmücken kann.

**Comment by henrybrink** [comment]
Idee:

<img width="540" alt="Icon" src="https://github.com/SE-TINF22B2/G5-DuoGradus/assets/20884220/8a60fa7b-8c3b-4b7d-8da6-ec6ae7df1224">

**Comment by benegamz** [comment]
Finde ich gar nicht schlecht. Was meinen die anderen dazu?

**Comment by henrybrink** [comment]
Kommentar von Ingo und Benedict: Es muss mehr aussehen wie ein Schuh

**Comment by wwwLuis** [comment]
![duo-gradus-logo-white](https://github.com/SE-TINF22B2/G5-DuoGradus/assets/91529471/d96f582e-04c9-4e86-a001-a05769919883)
![duo-gradus-logo-black](https://github.com/SE-TINF22B2/G5-DuoGradus/assets/91529471/5e09e46f-2e4d-458f-9644-0ff20e3cc8f5)
 justin und ich hatten letzte woche mal die erstellt

**Comment by henrybrink** [comment]
Das sieht ja fantastisch aus

**Comment by Jstn2004** [comment]
<p align="center">
  <img width="523" src="https://github.com/Jstn2004/Login/assets/135236159/0e961393-d04d-4a7b-97ed-37e91c011778">
</p>
<p align="center">
  <img width="523" src="https://github.com/SE-TINF22B2/G5-DuoGradus/assets/135236159/3b1cf236-348a-4483-a22f-28b7b1e2dc40">
</p>
<p align="center">
  <img width="523" src="https://github.com/SE-TINF22B2/G5-DuoGradus/assets/135236159/1c7ddb09-9bc4-47b9-910f-5c9f85edf77c">
</p>

Habe nochmal ein paar Veränderungen am Logo vorgenommen, wie findet ihr das?
