### ISSUE TITLE
Über API entscheiden

### ISSUE THREAD

**Issue by henrybrink** [SE-TINF22B2/G5-DuoGradus#38]
Für die Kommunikation zwischen Frontend- und Backend benötigen wir eine API. Es empielt sich diese vor Beginn der Entwicklung zu definieren / zumindest die technische Basis zu klären, damit wir Frontend und Backend unabhängig voneinander entwickeln können und zudem entscheiden können, welche Technologie wie benutzen müssen, damit wir die API umsetzen.

Erste Hintergrundinformationen befinden sich hier: [API im Wiki](https://github.com/SE-TINF22B2/G5-DuoGradus/wiki/API)

Aktuell stehen zur Auswahl
- REST
- GraphQL

Alternative Protokolle wären:
- SOAP
- JSON-RPC
- OData (Erweiterung von REST)

Allerdings empfehlen sich wie im Wiki beschrieben die ersten Optionen, besonders mit REST werden wahrscheinlich alle Erfahrungen haben (zudem ist bspw. die FitBit-API eine REST API)

**Comment by benedictweis** [comment]
Ich schließe dieses Issue jetzt da eine API vorhanden ist. Weitere Anpassungen daran können in separaten Issues besprochen werden.
