### ISSUE TITLE
[META] Integration mit Drittanbietern zur Datenerhebung

### ISSUE THREAD

**Issue by henrybrink** [SE-TINF22B2/G5-DuoGradus#51]
Diese Issue enthält eine Übersicht für alle Implementierungsschritte für die Integration von Drittanbietern.

**Sub-Tasks**
- [x] #136
- [x] #137
- [x] #138
- [x] #139
- [x] #140

**Comment by benedictweis** [comment]
Geschlossen da alle Aufgaben bearbeitet wurden
