### ISSUE TITLE
Technische Themen im backend

### ISSUE THREAD

**Issue by henrybrink** [SE-TINF22B2/G5-DuoGradus#61]
Diese Issue enthält alle für technische Themen (Framework-Konfiguration etc.) relevanten Issues.

**Sub-Topics**:
- [x] #65
- [x] #66
- [x] #92
- [x] Webserver Konfiguration
- [x] #226
- [x] Automatisierte Tests über GitHub Actions einrichten
- [x] #134
- [x] #135
- [x] #91 
- [x] #132

**Comment by benedictweis** [comment]
Geschlossen da alle Aufgaben bearbeitet wurden
