### ISSUE TITLE
[Backend] - Basic Project Skeleton

### ISSUE THREAD

**Issue by henrybrink** [SE-TINF22B2/G5-DuoGradus#64]
Um den Entwicklungsstarts des Projekts zu erleichtern sollte zunächst eine Projektbasis geschaffen werden, in die grundlegende Konfiguration des Frameworks durchgeführt wurde und bereits einige wichtige Basiselemente zur Verfügung stehen.

Diese Basis-Version sollte folgendes enthalten:

- [x] #65 
- [x] #66
- [x] #68 
- [x] #75
- [x] #73 
- [x] #91

Dieses Skeleton sollte bis zum 01.04.2024 zur Verfügung stehen, damit die Entwicklung in der Theoriephase parallel zu den normalen Vorlesungen erfolgen kann und der Last anderer Module angepasst werden kann.

**Comment by henrybrink** [comment]
Die Einrichtung der Basis-Umgebung ist derzeit noch nicht vollständig abgeschlossen, da das verwendete ORM (TypeORM) keine sinnvolle Möglichkeit für "Seeding" bietet. Außerdem ist es weniger flexibel als angenommen.

Als Mitigtation wird stattdessen "Prisma ORM" verwendet, die Einrichtung verzögert sich etwas.

Für die Authentifizierung wird zunächst (lokal) auf Basic Auth gesetzt, da dies in der Entwicklung am einfachsten umzusetzen ist. In einem separaten Schritt wird eine sinnvolle Authentifizierung eingebunden.

**Comment by benedictweis** [comment]
@henrybrink kann dieses issue geschlossen werden?

**Comment by henrybrink** [comment]
@benedictweis Ist die Prettier / ES-Lint Konfiguration schon fertig? Das macht doch @OG-NI?

**Comment by benedictweis** [comment]
Ja, sein Issue ist noch nicht geschlossen, hab mich nur gewundert weil hier alles abgehakt war 😅. Dieses Issue kann noch offen bleiben.

**Comment by benedictweis** [comment]
Closed as all tasks are now completed
