### ISSUE TITLE
[Frontend] Rankingpage

### ISSUE THREAD

**Issue by Jstn2004** [SE-TINF22B2/G5-DuoGradus#84]
Es wird die Entwicklung einer Rankingseite gefordert, die es Benutzern ermöglicht, ihre persönlichen Erfolgsserien mit denen ihrer Freunde oder allen anderen Nutzern zu vergleichen.

Sub-Tasks

- [ ] Rankingswitch
- [x] Rankingtable
  - [x] Usercard

**Comment by wwwLuis** [comment]
Rankingswitch erstmal aufgeschoben, da die Rangliste unter Freunden optional ist
