### ISSUE TITLE
Dokumentation der Konfiguration

### ISSUE THREAD

**Issue by henrybrink** [SE-TINF22B2/G5-DuoGradus#91]
Die bisherige Konfiguration des Projekts ist zu dokumentieren, insbesondere die verwendeten Bibliotheken, sowie die Konzepte, die für Authentifizierung / Autorisierung genutzt werden.

**Comment by benedictweis** [comment]
Ich denke diese Dokumentation gehört in den `backend/docs` folder, vielleicht als `technologies.md` o.ä.

**Comment by benedictweis** [comment]
Wird geschlossen, da die meisten wichtigen Themen behandelt wurden.
