### ISSUE TITLE
Logging-Konfiguration

### ISSUE THREAD

**Issue by henrybrink** [SE-TINF22B2/G5-DuoGradus#92]
Das Projekt soll ein einheitliches Framework für Logging verwenden, insbesondere soll dies eine Konfiguration des Log-Levels ermöglichen, sodass z.B. in Production sensitive Logs nicht enthalten sind, sowie unnötige Logs vermieden werden können.

Möglicherweise ist keine wirkliche Konfiguration möglich, da NestJS bereits Logging-Möglichkeiten mitbringt:
https://docs.nestjs.com/techniques/logger#using-the-logger-for-application-logging

- [x] integriertes Logging in NestJS verstehen
- [x] Logging-Konfiguration ggf. anpassen
- [x] Logging-Klassen bauen
- [x] Entscheidungen über Format der Logs treffen

**Comment by OG-NI** [comment]
Wir werden zunächst den integrierten Logger von NestJS verwenden. Dieser wird dann durch ein Interface abstrahiert, damit er später durch andere Technologien ausgetauscht werden kann.

**Comment by benedictweis** [comment]
Da diese Entscheidung nun getroffen wurde, muss nur noch ein Eintrag in `backend/docs` stattfinden. Könntest du das übernehmen @OG-NI?

**Comment by OG-NI** [comment]
Dokumentation ist hinzugefügt. Ich habe mich doch für ein Interface entschieden, damit der Logger später einfacher ausgetauscht werden kann. Der `ConsoleLogger` von NestJS passt zu diesem Interface und kann vorerst verwendet werden.
