### ISSUE TITLE
[Meta] (gesprochene) Sprache die im Projekt verwendet wird

### ISSUE THREAD

**Issue by benedictweis** [SE-TINF22B2/G5-DuoGradus#96]
Hallo zusammen, mir ist aufgefallen was wir in unserem Wiki nicht eindeutig festlegen in welcher gesprochenen Sprache wir unser Projekt dokumentieren. Beispiel hierfür: einige der Issues sind auf Englisch, andere sind auf Deutsch. Wir sollten uns gemeinsam überlegen wo wir welche der beiden Sprachen verwenden wollen und dies dann im [Wiki](https://github.com/SE-TINF22B2/G5-DuoGradus/wiki) unter [Projekthandbuch](https://github.com/SE-TINF22B2/G5-DuoGradus/wiki/📃-Projekthandbuch) festhalten.

Dieses Issue kann geschlossen werden wenn:

1. [x] Gemeinsam diskutiert wurde, wo welche Sprache verwendet wird
2. [x] Ein Wiki Eintrag mit dem Ergebnis der Diskussion angelegt wurde

Mein Vorschlag:

- **Code**: Komplett auf Englisch, auch die direkte Dokumentation wie Kommentare, Beispiele etc.
- **Discussions, Issues und Pull Requests**: auf Deutsch
- **Wiki**: auf Deutsch, wie auch bisher,
- **`README` sowie [`docs`](https://github.com/SE-TINF22B2/G5-DuoGradus/tree/main/docs)** auch auf Deutsch
- **Commit messages** sind egal da nur noch squash merges möglich sind

Bereits in der anderen Sprache geschriebene Dokumente im `docs` Verzeichnis müssen wir meiner Meinung nach nicht nochmal schreiben.

Was meint ihr dazu?

**Comment by Jstn2004** [comment]
Finde ich gut

**Comment by benedictweis** [comment]
@henrybrink, @OG-NI was meint ihr dazu?

**Comment by benedictweis** [comment]
Nach einigen PR reviews bin ich bei PRs doch für English. Das fühlt sich sinnvoller an, da der Code ja auch auf English ist.
