### ISSUE TITLE
Deployment Lösung festlegen

### ISSUE THREAD

**Issue by benedictweis** [SE-TINF22B2/G5-DuoGradus#98]
Je früher eine deployment Lösung ausgesucht wird, desto früher können manuelle end to end tests stattfinden. Zudem wird dadurch dem backend und frontend viel Zeit gegeben um sich an die Lösung anzupassen. Ich schlage [docker compose](https://docs.docker.com/compose/) als deployment Lösung vor, da es dem Branchenstandard entspricht.

Die folgenden Schritte müssen bearbeitet werden bevor dieses Issue geschlossen werden kann:

- [ ] `Dockerfile` im frontend und backend anlegen
- [ ] `docker-compose.yaml` im root folder anlegen
- [ ] **!!! Sowohl frontend und backend per [environment variablen](https://medium.com/chingu/an-introduction-to-environment-variables-and-how-to-use-them-f602f66d15fa) konfigurierter machen !!!** (insbesondere Dinge wie hostname und port anpassbar machen, sowie Datenbank Verbindungen sofern vorhanden)

**Comment by henrybrink** [comment]
Ich werde mich später zu einer möglichen Deployment-Lösung äußern, wir können den vServer nutzen den ich für die MySQL-Instanz aufgesetzt habe und dort ein Test-Deployment laufen lassen.

Ob wir das über Docker machen, oder über eine andere Lösung können wir noch diskutieren :)

**Comment by benedictweis** [comment]
Es geht mir um die Möglichkeiten wie wir dieses Projekt bestmöglich ausliefen können. Es sollte möglich sein mit nur einem Command (`docker compose up`) und ohne externe dependencies das Projekt zum laufen zu bekommen. Für ein Test-Deloyment was nicht produktiv eingesetzt wird und keine Möglichkeiten zur Skalierung etc. haben muss können wir selbstverständlich ein shell script oder einen Makefile zur verfügung stellen die das gesamte Projekt unter Verwendung der lokalen dependencies lokal ausführt.
